"""A program where we have to guess the number generated by the computer """

import random

def guessnum(x):
    random_num = random.randint(0 , x)
    guessnum = 0
    
    while guessnum != random_num:
        guessnum = int(input(f"Guess the number between 0 and {x} : "))
        if guessnum > random_num:
            print("Too High, guess again")
        elif guessnum < random_num :
            print("Too Low, guess again")

    print(f"Yaay! You guessed the number correctly, the number was {random_num}")

guessnum(20)