"""A program where the computer guesses the number generated by the us."""

import random

num = int(input("Enter the number which you have guessed. Don't Worry , the computer can't see it ;) : "))
print(f"You have entered the number : {num}")

def guess(x):
    lnum = 0
    hnum = x
    response = ''
    
    while response != 'c':
        if lnum != hnum:
            guess = guess = random.randint(lnum , hnum)
        else :
            guess = lnum
        
        response = input(f"Is {guess} too high (H) , low(L) or was it correct(C) ? : ").lower()
        if response == 'h':
            hnum =guess - 1 

        elif response == 'l':
            lnum = guess + 1 

    print(f'Yay! The computer guessed your number, {guess}, correctly!')

guess(100)
